name: filmku
description: "Movie App using TMDB"

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

  # State Management
  get: ^4.6.6


  # API/Networking
  http: ^1.2.2

  # Helpers
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0

  #Video Player
  youtube_player_flutter: ^9.0.3

  #DB
  hive_flutter: ^1.1.0

  # Image
  cached_network_image: ^3.4.1

  #connevtivity
  connectivity_plus: ^6.0.5
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env

